<a href="https://colab.research.google.com/github/komal021406/ML/blob/main/Assignment_Python_for_DS_Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Assignment

In [ ]:
import numpy as np

### MCQ1

In [ ]:
np.random.randint(1, 101, size=(4, 4)).shape

(4, 4)

### MCQ2

In [ ]:
A = np.array([1, 2, 3])
B = A*2
B

array([2, 4, 6])

In [ ]:
import numpy as np

A = np.array([1, 2, 3])
B= np.array([1, 2, 3])


A*B

array([1, 4, 9])

In [ ]:
import numpy as np



A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = A[1:3, 0:2]



B[0, 0] = 100

print(A)

[[  1   2   3]
 [100   5   6]
 [  7   8   9]]


In [ ]:
A[1,0]

100

In [ ]:
B[0,0]

100

In [ ]:
id(B[])

138058288059696

In [ ]:
id(A[])

138058288055376

In [ ]:
print(id(B))
print(id(A))

138059045394096
138059045390352


### MCQ3

In [ ]:
matrix = np.eye(4)

In [ ]:
np.diagonal(matrix)

array([1., 1., 1., 1.])

In [ ]:
matrix = np.eye(4)

result = np.diagonal(matrix)

print(result)

[1. 1. 1. 1.]


### MCQ4

In [ ]:
A = np.array([[1, 2], [3, 4]])

In [ ]:
A.shape

(2, 2)

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
A = np.array([[1, 2], [3, 4]])

B = A.T

B

array([[1, 3],
       [2, 4]])

### MCQ5

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5], [6]])
C = np.array([5, 6])

In [ ]:
print(A)
print()
print(B)
print()
print(C)

[[1 2]
 [3 4]]

[[5]
 [6]]

[5 6]


In [ ]:
D = np.hstack((A, B))
E = np.vstack((A, C))

print(D)
print()
print(E)

[[1 2 5]
 [3 4 6]]

[[1 2]
 [3 4]
 [5 6]]


### MCQ6

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 7], [6, 8]])

print(A)
print()
print(B)
print()

[[1 2]
 [3 4]]

[[5 7]
 [6 8]]



In [ ]:
D = np.matmul(A, B)
E = np.multiply(A, B)

print(D)
print()
print(E)

[[17 23]
 [39 53]]

[[ 5 14]
 [18 32]]


In [ ]:
D = np.matmul(A, B)
F = np.dot(A, B)

print(D)
print()
print(F)

[[17 23]
 [39 53]]

[[17 23]
 [39 53]]


### MCQ7

In [ ]:
A = np.array([10, 20, 30, 40])

print(A)

[10 20 30 40]


In [ ]:
mask = (A >= 20) & (A <= 30)

In [ ]:
A[mask]

array([20, 30])

### MCQ8

In [ ]:
arr = np.array([1, 2, -1, 4, 5])

In [ ]:
min_index = np.argmin(arr)
max_index = np.argmax(arr)

print(min_index, max_index)

2 4


In [ ]:
indices = np.where(arr > 3)

print(indices)

(array([3, 4], dtype=int64),)


In [ ]:
np.sort(arr)

array([-1,  1,  2,  4,  5])

### MCQ9

In [ ]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### MCQ10

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

result = np.cross(arr1, arr2)

print(result)

[-3  6 -3]


### FF1

In [ ]:
# Create a 5x5 matrix filled with random integers between 1 and 100
A = np.random.randint(1, 101, size=(5, 5))

print(A)

[[ 17  18  26  87  81]
 [ 58  62  29  87  61]
 [ 20   0  82  81   6]
 [ 75  87 100  58  51]
 [ 90  37  49  92  97]]


In [ ]:
# Calculate the mean and standard deviation of the matrix and print them.
mean = np.mean(A)
std = np.std(A)

print(mean)
print(std)

43.72
24.768560717167237


### FF2

In [ ]:
# Create a 5x5 identity matrix and add a scalar value of 5 to it
I = np.eye(5)

aug_I = I + 5

aug_I

array([[6., 5., 5., 5., 5.],
       [5., 6., 5., 5., 5.],
       [5., 5., 6., 5., 5.],
       [5., 5., 5., 6., 5.],
       [5., 5., 5., 5., 6.]])

In [ ]:
# Multiply the resulting matrix with a 5x1 column vector filled with random integers between 1 and 10
rand_vec = np.random.randint(1, 11, size=(5, 1))

result = np.matmul(aug_I, rand_vec)

print(result)

[[173.]
 [166.]
 [175.]
 [173.]
 [171.]]


### FF3

In [ ]:
# Create two 3x3 matrices filled with random integers between 1 and 100
A = np.random.randint(1, 101, size=(3, 3))
B = np.random.randint(1, 101, size=(3, 3))

print(A)
print()
print(B)

[[54 78 76]
 [85 99 43]
 [27 85 75]]

[[ 5 47 26]
 [60 50 47]
 [68 68 24]]


In [ ]:
# Compute their element-wise multiplication, and print the resulting matrix
result = np.multiply(A, B)

print(result)

[[ 270 3666 1976]
 [5100 4950 2021]
 [1836 5780 1800]]


### FF4

In [ ]:
# Create a 1000-element array of random integers between 1 and 1000
arr = np.random.randint(1, 1001, 1000)

print(arr)

[ 128  177  493  303  943  183  779  504  321   57  526  105  251  275
  411  509  115  179  112  542  496  722  808  607  479  935  518  699
  536  777  310  372  943  329  872  474  895  180  230  168  231  575
  761  452  997  739  730  693  706  362  183    7  293  897  456  392
  407  402  482  524  942  572  231  842  560  644  967  285  755  130
  634  300  156  624  940  202  154  871  248  937  942   74    8  248
  589  768  858  217  308  802  279  479   86   25  625  637  426  203
  722   37  329  865  712    6  174  695   36  729  452  738  500  907
  311  102  844  908  358  993  466   36  885  669  626  128  687  735
  138  324  854  668  865  239    5  909  754  552  748  778  916  704
  145  765  775  710  114  874  642  721  718  353  342  232  890  488
  216  663  962  714  298  631  390  498  219  359  652  545   93 1000
  558  112  378  805  851  885  587  444  976  232  892  547  879  825
  782  765  148   43  237   43  298  250  866  460  730  236  453  738
  185 

In [ ]:
# Calculate the cumulative sum of the array
cum_arr = np.cumsum(arr)

print(cum_arr)

[   128    305    798   1101   2044   2227   3006   3510   3831   3888
   4414   4519   4770   5045   5456   5965   6080   6259   6371   6913
   7409   8131   8939   9546  10025  10960  11478  12177  12713  13490
  13800  14172  15115  15444  16316  16790  17685  17865  18095  18263
  18494  19069  19830  20282  21279  22018  22748  23441  24147  24509
  24692  24699  24992  25889  26345  26737  27144  27546  28028  28552
  29494  30066  30297  31139  31699  32343  33310  33595  34350  34480
  35114  35414  35570  36194  37134  37336  37490  38361  38609  39546
  40488  40562  40570  40818  41407  42175  43033  43250  43558  44360
  44639  45118  45204  45229  45854  46491  46917  47120  47842  47879
  48208  49073  49785  49791  49965  50660  50696  51425  51877  52615
  53115  54022  54333  54435  55279  56187  56545  57538  58004  58040
  58925  59594  60220  60348  61035  61770  61908  62232  63086  63754
  64619  64858  64863  65772  66526  67078  67826  68604  69520  70224
  7036

In [ ]:
# Print the 10th, 100th, and 500th elements of the cumulative sum array
print(cum_arr[9])
print(cum_arr[99])
print(cum_arr[499])

3888
47879
252564


### FF5

In [ ]:
# Create a 10x10 matrix filled with random integers between 1 and 100
A = np.random.randint(1, 101, size=(10, 10))

A

array([[ 53,  11,  56,  63,  90,   9, 100,  96,  29,  30],
       [ 60,  71,  31,  47,  28,  14,  10,  68,  94,  46],
       [ 62,  25,  90,  80,  11,  15,  12,   4,  22,  11],
       [ 95,  25,  23,  64,  26,  37,  10,  24,  67,  50],
       [ 46,  99,  80,  33,  76,  22,  56,  81,  38,  37],
       [ 77,  94,  32,  21,  33,   9,  70,  53,  78,  47],
       [  4,  58,  24,  27,  11,   2,  83,  22,  23,  86],
       [ 29,  12, 100,  99,  68,  78,  37,  35,  49,  28],
       [ 59,  13,   1,  99,  98,  22,  16,  24,  23,  71],
       [ 92,   4,  57,  71,  77,  85,  97,  39,  81,  99]])

In [ ]:
# Find the minimum and maximum values of the matrix along with their indices
min_val = np.min(A)
max_val = np.max(A)

print(min_val, max_val)

1 100


In [ ]:
min_val_idx = np.argmin(A)
max_val_idx = np.argmax(A)

print(min_val_idx, max_val_idx)

82 6


In [ ]:
min_idx = np.unravel_index(np.argmin(A), A.shape)
max_idx = np.unravel_index(np.argmax(A), A.shape)

print(min_idx, max_idx)

(8, 2) (0, 6)


### FF6

In [ ]:
# Create a 5x5 matrix filled with random floats between 0 and 1
A = np.random.random(size=(5, 5))
# A = np.random.rand(5, 5)

print(A)

[[0.88724223 0.98864142 0.22230032 0.66341337 0.08823717]
 [0.90437875 0.98850822 0.33748577 0.63544255 0.6640637 ]
 [0.53954694 0.53985952 0.12451775 0.5115666  0.69385013]
 [0.54410975 0.05987213 0.18998327 0.5186918  0.0562846 ]
 [0.57163745 0.06070574 0.30295695 0.19475488 0.11622983]]


In [ ]:
# Replace the maximum value in the matrix with 0 and print the original and modified matrices
max_index = np.unravel_index(np.argmax(A), A.shape)

print(max_index)

(0, 1)


In [ ]:
A[max_index] = 0

A

array([[0.88724223, 0.        , 0.22230032, 0.66341337, 0.08823717],
       [0.90437875, 0.98850822, 0.33748577, 0.63544255, 0.6640637 ],
       [0.53954694, 0.53985952, 0.12451775, 0.5115666 , 0.69385013],
       [0.54410975, 0.05987213, 0.18998327, 0.5186918 , 0.0562846 ],
       [0.57163745, 0.06070574, 0.30295695, 0.19475488, 0.11622983]])

In [ ]:
max_val = np.max(A)

A[A == max_val] = 0

In [ ]:
A

array([[0.88724223, 0.        , 0.22230032, 0.66341337, 0.08823717],
       [0.90437875, 0.        , 0.33748577, 0.63544255, 0.6640637 ],
       [0.53954694, 0.53985952, 0.12451775, 0.5115666 , 0.69385013],
       [0.54410975, 0.05987213, 0.18998327, 0.5186918 , 0.0562846 ],
       [0.57163745, 0.06070574, 0.30295695, 0.19475488, 0.11622983]])

### FF7

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
B = A[1:3, 0:2]

B[0, 0] = 100

B

array([[100,   5],
       [  7,   8]])

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = A[1:3, 0:2]

B[0, 0] = 100

print(A)

[[  1   2   3]
 [100   5   6]
 [  7   8   9]]


### FF8

In [ ]:
# Create a 1D array of 20 elements with random integers between 1 and 100
arr = np.random.randint(0, 2, size)

arr

array([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [ ]:
np.count_nonzero(arr, axis=0)

7

In [ ]:
arr % 2 == 1

array([ True,  True,  True, False, False, False,  True,  True,  True,
       False, False, False, False, False,  True, False, False, False,
       False, False])

In [ ]:
# Calculate the number of even and odd elements in the array and print the result
even_count = np.count_nonzero(arr % 2 == 0)
odd_count = np.count_nonzero(arr % 2 == 1)

print(even_count)
print()
print(odd_count)

13

7


### FF9

In [ ]:
A = np.arange(1, 17).reshape(4, 4)

print(A)

B = A[:, ::-1]

print()
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


### FF10

In [ ]:
# Create a 2D array of size 8x8, where the outer border elements are set to 1 and the inner elements are set to 0
A = np.ones((8, 8))

A[1:7, 1:7] = 0

print(A)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
A

array([[0, 1],
       [2, 3]])

In [ ]:
A = np.array([[0, 1], [2, 3]])

np.count_nonzero(A, axis=0)

array([1, 2], dtype=int64)

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])